### ISSUE TITLE
What license is this?

### ISSUE THREAD

**Issue by kjarvi** [jtarchie/underscore-lua#10]
Am I free to use this in my code? There's no license attached, but I would love to use this.

**Comment by jtarchie** [comment]
Let me get back to you on this, as I need to add it to the project.

It looks like underscorejs license is MIT. I like that.

**Comment by kjarvi** [comment]
Alright, perfect, thank you. Adding it to the project would be a great help. Kudos for all your work!

**Comment by jtarchie** [comment]
Closing because added LICESNE
