### ISSUE TITLE
underscore string functions

### ISSUE THREAD

**Issue by jtarchie** [jtarchie/underscore-lua#2]
It looks like there is awesome underscore JS library the extends into string functions.

https://github.com/epeli/underscore.string

What would it take to add these features?

**Comment by emberian** [comment]
Are you actively working on this? If not I'd like to adopt it as a 24pr project.

**Comment by jtarchie** [comment]
Nothing yet.

I was going to tackle this as one function at a time, rather than a whole version update. If you want to make pull requests, please do.

I don't think I have to say for your benefit, but if anyone else is reading, please write tests! :smiley:

**Comment by emberian** [comment]
Work being done on https://github.com/cmr/underscore-lua/tree/string. I'll squash it all down as it approaches completeness and send a PR, sound good?
