### ISSUE TITLE
_.invoke with self parameter

### ISSUE THREAD

**Issue by vertti** [jtarchie/underscore-lua#8]
I'd like something like this to work:

   __.invoke(props, "setVisible", visible)

where `props` is a table and for each element in that table I'd like an invoke like 

```
 prop:setVisible(visible)
```

in other words that `self` could be passed as the first argument to the function.

**Comment by jtarchie** [comment]
Not a bad idea, but I'd hate to change the entire expectation of invoke to just support self. Would a method `invokeSelf` be worth it?

**Comment by vertti** [comment]
That's fine with me, I seem to run into this use case often. `invokeWithSelf` might be a better name as it doesn't invoke self but does an invoke and supplies self as parameter.

**Comment by jtarchie** [comment]
You know it turns out, that `invoke` already supported this. The function being called has to either have `self` as the first argument or be defined via the colon syntax.

The following passes in the test suite:

``` lua
  local object = {count=0}
  function object:incr()
    self.count = self.count + 1
    return self.count
  end

  it("passes the object to the method that is being invoked", function()
    local array = {object, object, object}
    assert.same(_.invoke(array, 'incr'), {1,2,3})
  end)
```

Did it not work for you when trying `_.invoke(props, "setVisible", visible)`?

**Comment by jtarchie** [comment]
@vertti were you able to test the above with your code?

**Comment by jtarchie** [comment]
@vertti any feedback? Otherwise I am closing the ticket.

**Comment by vertti** [comment]
Yes, I don't know what I originally did wrong but `invoke` seems to work fine with self. Thanks.
